import type { Proof, RequirementData, Resource } from "@/lib/api/types";
export const requirement: Resource<RequirementData> = {
  id: "req-test",
  data: {
    status: "COMPILED",
    original_prompt: "Research test companies",
    requirement_spec: {
      version: "1.0",
      entity_type: "company",
      goal: "Research test companies",
      fields: [
        {
          key: "company_name",
          label: "Company",
          data_type: "text",
          required: true,
          origin: "user",
          description: null,
        },
      ],
      filters: [],
      geography: ["India"],
      time_window: null,
      source_hints: [],
      limit: 20,
      refresh: null,
    },
    schema: {
      id: "schema-test",
      version: "1.0",
      entity_type: "company",
      fields: [],
      schema_hash: "12345678",
    },
    trust_contract: {
      version: "1.0",
      require_evidence_anchor: true,
      minimum_independent_sources: 1,
      prefer_first_party: true,
      allow_secondary_sources: true,
      allow_single_source_output: true,
      preserve_conflicts: true,
      strict_required_fields: false,
      max_source_age_days: null,
      max_search_queries: 5,
      max_pages: 60,
      max_browser_pages: 0,
      max_llm_calls: 80,
      max_run_seconds: 180,
      max_estimated_cost_usd: "3.00",
    },
    version: 1,
    confirmed: false,
    compiler_metadata: {
      compiler: {
        provider_name: "fixture",
        model_name: "fixture",
        reference_date: "2026-09-30T00:00:00Z",
        compiled_at: "2026-09-30T00:00:00Z",
      },
      ambiguities: [],
      assumptions: [],
    },
  },
};
export const proof: Proof = {
  dataset_version_id: "version-test",
  entity_id: "entity-test",
  field_key: "funding_amount",
  canonical_value: { amount: "4500000", currency: "USD" },
  trust_status: "CONFLICTING",
  resolution: {
    reason: "material_disagreement",
    selected_claim_id: "claim-a",
    independent_sources: 2,
    claim_ids: ["claim-a", "claim-b"],
    conflicting_claim_ids: ["claim-b"],
  },
  claims: ["a", "b"].map((id, index) => ({
    id: `claim-${id}`,
    raw_value: index ? "$5M" : "$4.5M",
    normalized_value: {
      amount: index ? "5000000" : "4500000",
      currency: "USD",
    },
    source_id: `source-${id}`,
    source_url: `https://example-${id}.test/announcement`,
    raw_document_id: `document-${id}`,
    content_hash: `hash-${id}`,
    retrieved_at: "2026-09-30T00:00:00Z",
    extraction_method: "deterministic",
    validation_flags: [],
    evidence: {
      type: "TEXT_SPAN",
      locator: { char_start: 0, char_end: 21, verified: true },
      quote: index ? "Test company raised $5M." : "Test company raised $4.5M.",
      verification_status: "EXACT",
    },
    acquisition: { synthetic: true, first_party: index === 0 },
  })),
  conflict: {
    id: "conflict-test",
    status: "OPEN",
    details: { claim_ids: ["claim-a", "claim-b"] },
    selected_claim_id: null,
  },
};
